-- ============================================================================
-- PROJETO: AURUM BANKING
-- ETAPA 1: MODELAGEM E SCRIPT DDL (ORACLE DATABASE / SQL DEVELOPER)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. ELIMINAÇÃO DE TABELAS (DROP CASCADE) PARA REINICIALIZAÇÃO LIMPA
-- ----------------------------------------------------------------------------
DROP TABLE TB_PROGRESSO_AULA CASCADE CONSTRAINTS;
DROP TABLE TB_AULA CASCADE CONSTRAINTS;
DROP TABLE TB_SOLICITACAO_TRANSACAO CASCADE CONSTRAINTS;
DROP TABLE TB_GUARDIAO CASCADE CONSTRAINTS;
DROP TABLE TB_COFRE_TEMPORAL CASCADE CONSTRAINTS;
DROP TABLE TB_TRANSACAO CASCADE CONSTRAINTS;
DROP TABLE TB_POSICAO_CRIPTO CASCADE CONSTRAINTS;
DROP TABLE TB_CRIPTOATIVO CASCADE CONSTRAINTS;
DROP TABLE TB_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE TB_USUARIO CASCADE CONSTRAINTS;
DROP TABLE TB_CARTEIRA CASCADE CONSTRAINTS;

-- ----------------------------------------------------------------------------
-- 2. CRIAÇÃO DAS TABELAS E RESTRIÇÕES
-- ----------------------------------------------------------------------------

-- TABELA: TB_CARTEIRA
-- Armazena as carteiras digitais vinculadas a usuários e empresas
CREATE TABLE TB_CARTEIRA (
    ID_CARTEIRA              NUMBER GENERATED ALWAYS AS IDENTITY,
    DS_ENDERECO_DIGITAL      VARCHAR2(100) NOT NULL,
    VL_SALDO_DISPONIVEL_BRL  NUMBER(18, 2) DEFAULT 0.00 NOT NULL,
    DH_CRIACAO               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_TB_CARTEIRA PRIMARY KEY (ID_CARTEIRA),
    CONSTRAINT UK_CARTEIRA_ENDERECO UNIQUE (DS_ENDERECO_DIGITAL),
    CONSTRAINT CK_CARTEIRA_SALDO_POSITIVO CHECK (VL_SALDO_DISPONIVEL_BRL >= 0)
);

-- TABELA: TB_USUARIO
-- Armazena os dados cadastrais, perfil de acesso e limites dos usuários pessoa física
CREATE TABLE TB_USUARIO (
    ID_USUARIO               NUMBER GENERATED ALWAYS AS IDENTITY,
    NM_COMPLETO              VARCHAR2(150) NOT NULL,
    NR_CPF                   VARCHAR2(14) NOT NULL,
    DS_EMAIL                 VARCHAR2(150) NOT NULL,
    DS_SENHA_HASH            VARCHAR2(255) NOT NULL,
    DT_NASCIMENTO            DATE NOT NULL,
    DS_MODO_INTERFACE        VARCHAR2(20) DEFAULT 'INICIANTE' NOT NULL,
    VL_LIMITE_MENSAL         NUMBER(18, 2) DEFAULT 5000.00 NOT NULL,
    FL_KYC_APROVADO          CHAR(1) DEFAULT 'N' NOT NULL,
    ID_CARTEIRA              NUMBER NOT NULL,
    DH_CADASTRO              TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_TB_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO_CPF UNIQUE (NR_CPF),
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE (DS_EMAIL),
    CONSTRAINT UK_USUARIO_CARTEIRA UNIQUE (ID_CARTEIRA),
    CONSTRAINT FK_USUARIO_CARTEIRA FOREIGN KEY (ID_CARTEIRA) 
        REFERENCES TB_CARTEIRA (ID_CARTEIRA),
    CONSTRAINT CK_USUARIO_MODO_INTERFACE CHECK (DS_MODO_INTERFACE IN ('INICIANTE', 'AVANCADO')),
    CONSTRAINT CK_USUARIO_KYC CHECK (FL_KYC_APROVADO IN ('S', 'N')),
    CONSTRAINT CK_USUARIO_LIMITE_POSITIVO CHECK (VL_LIMITE_MENSAL >= 0)
);

-- TABELA: TB_EMPRESA
-- Armazena pessoas jurídicas correntistas e seu vínculo com o Usuário Master
CREATE TABLE TB_EMPRESA (
    ID_EMPRESA              NUMBER GENERATED ALWAYS AS IDENTITY,
    DS_RAZAO_SOCIAL          VARCHAR2(180) NOT NULL,
    NR_CNPJ                  VARCHAR2(18) NOT NULL,
    DS_EMAIL_CORPORATIVO     VARCHAR2(150) NOT NULL,
    FL_STATUS_ATIVO          CHAR(1) DEFAULT 'S' NOT NULL,
    ID_USUARIO_MASTER        NUMBER NOT NULL,
    ID_CARTEIRA              NUMBER NOT NULL,
    DH_CRIACAO               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_TB_EMPRESA PRIMARY KEY (ID_EMPRESA),
    CONSTRAINT UK_EMPRESA_CNPJ UNIQUE (NR_CNPJ),
    CONSTRAINT UK_EMPRESA_EMAIL UNIQUE (DS_EMAIL_CORPORATIVO),
    CONSTRAINT UK_EMPRESA_CARTEIRA UNIQUE (ID_CARTEIRA),
    CONSTRAINT FK_EMPRESA_USUARIO_MASTER FOREIGN KEY (ID_USUARIO_MASTER) 
        REFERENCES TB_USUARIO (ID_USUARIO),
    CONSTRAINT FK_EMPRESA_CARTEIRA FOREIGN KEY (ID_CARTEIRA) 
        REFERENCES TB_CARTEIRA (ID_CARTEIRA),
    CONSTRAINT CK_EMPRESA_STATUS_ATIVO CHECK (FL_STATUS_ATIVO IN ('S', 'N'))
);

-- TABELA: TB_CRIPTOATIVO
-- Catálogo de criptomoedas e tokens negociados na plataforma Aurum
CREATE TABLE TB_CRIPTOATIVO (
    ID_CRIPTOATIVO           NUMBER GENERATED ALWAYS AS IDENTITY,
    NM_CRIPTOATIVO           VARCHAR2(100) NOT NULL,
    CD_SIGLA                 VARCHAR2(10) NOT NULL,
    DS_LOGO_URL              VARCHAR2(255),
    VL_PRECO_ATUAL_BRL       NUMBER(18, 4) NOT NULL,
    PC_VARIACAO_24H          NUMBER(8, 4) DEFAULT 0.0000 NOT NULL,
    FL_ATIVO_NEGOCIACAO      CHAR(1) DEFAULT 'S' NOT NULL,
    DH_ULTIMA_ATUALIZACAO    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_TB_CRIPTOATIVO PRIMARY KEY (ID_CRIPTOATIVO),
    CONSTRAINT UK_CRIPTOATIVO_SIGLA UNIQUE (CD_SIGLA),
    CONSTRAINT CK_CRIPTO_PRECO_POSITIVO CHECK (VL_PRECO_ATUAL_BRL >= 0),
    CONSTRAINT CK_CRIPTO_ATIVO_NEGOCIACAO CHECK (FL_ATIVO_NEGOCIACAO IN ('S', 'N'))
);

-- TABELA: TB_POSICAO_CRIPTO
-- Saldo consolidado de cada criptoativo pertencente a uma carteira
CREATE TABLE TB_POSICAO_CRIPTO (
    ID_POSICAO              NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CARTEIRA              NUMBER NOT NULL,
    ID_CRIPTOATIVO           NUMBER NOT NULL,
    QT_TOTAL                 NUMBER(24, 8) DEFAULT 0.00000000 NOT NULL,
    DH_ULTIMA_MOVIMENTACAO   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_TB_POSICAO_CRIPTO PRIMARY KEY (ID_POSICAO),
    CONSTRAINT UK_POSICAO_CARTEIRA_CRIPTO UNIQUE (ID_CARTEIRA, ID_CRIPTOATIVO),
    CONSTRAINT FK_POSICAO_CARTEIRA FOREIGN KEY (ID_CARTEIRA) 
        REFERENCES TB_CARTEIRA (ID_CARTEIRA),
    CONSTRAINT FK_POSICAO_CRIPTOATIVO FOREIGN KEY (ID_CRIPTOATIVO) 
        REFERENCES TB_CRIPTOATIVO (ID_CRIPTOATIVO),
    CONSTRAINT CK_POSICAO_QTDE_POSITIVA CHECK (QT_TOTAL >= 0)
);

-- TABELA: TB_TRANSACAO
-- Livro de registros contábeis e operacionais (Auditável)
CREATE TABLE TB_TRANSACAO (
    ID_TRANSACAO             NUMBER GENERATED ALWAYS AS IDENTITY,
    TP_TRANSACAO             VARCHAR2(30) NOT NULL,
    ST_TRANSACAO             VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    DH_TRANSACAO             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    VL_MOVIMENTADO_BRL       NUMBER(18, 2) NOT NULL,
    QT_CRIPTO                NUMBER(24, 8) DEFAULT 0.00000000 NOT NULL,
    VL_COTACAO_MOMENTO       NUMBER(18, 4) DEFAULT 0.0000 NOT NULL,
    VL_TAXA_OPERACAO         NUMBER(18, 2) DEFAULT 0.00 NOT NULL,
    ID_CARTEIRA              NUMBER NOT NULL,
    ID_CRIPTOATIVO           NUMBER,
    
    CONSTRAINT PK_TB_TRANSACAO PRIMARY KEY (ID_TRANSACAO),
    CONSTRAINT FK_TRANSACAO_CARTEIRA FOREIGN KEY (ID_CARTEIRA) 
        REFERENCES TB_CARTEIRA (ID_CARTEIRA),
    CONSTRAINT FK_TRANSACAO_CRIPTOATIVO FOREIGN KEY (ID_CRIPTOATIVO) 
        REFERENCES TB_CRIPTOATIVO (ID_CRIPTOATIVO),
    CONSTRAINT CK_TRANSACAO_TIPO CHECK (TP_TRANSACAO IN (
        'COMPRA', 'VENDA', 'TRANSFERENCIA_INTERNA', 
        'DEPOSITO_FIAT', 'SAQUE_FIAT', 'PAGAMENTO_TAXA'
    )),
    CONSTRAINT CK_TRANSACAO_STATUS CHECK (ST_TRANSACAO IN (
        'PENDENTE', 'PROCESSANDO', 'CONCLUIDA', 'FALHA', 'CANCELADA'
    )),
    CONSTRAINT CK_TRANSACAO_VALOR_BRL CHECK (VL_MOVIMENTADO_BRL >= 0),
    CONSTRAINT CK_TRANSACAO_QT_CRIPTO CHECK (QT_CRIPTO >= 0),
    CONSTRAINT CK_TRANSACAO_COTACAO CHECK (VL_COTACAO_MOMENTO >= 0),
    CONSTRAINT CK_TRANSACAO_TAXA CHECK (VL_TAXA_OPERACAO >= 0)
);

-- TABELA: TB_COFRE_TEMPORAL
-- Funcionalidade de bloqueio programado de ativos para resgate futuro
CREATE TABLE TB_COFRE_TEMPORAL (
    ID_COFRE                 NUMBER GENERATED ALWAYS AS IDENTITY,
    NM_OBJETIVO              VARCHAR2(100) NOT NULL,
    DT_CRIACAO               DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    DT_LIBERACAO             DATE NOT NULL,
    QT_BLOQUEADA             NUMBER(24, 8) NOT NULL,
    ST_COFRE                 VARCHAR2(20) DEFAULT 'BLOQUEADO' NOT NULL,
    ID_CARTEIRA              NUMBER NOT NULL,
    ID_CRIPTOATIVO           NUMBER NOT NULL,
    
    CONSTRAINT PK_TB_COFRE_TEMPORAL PRIMARY KEY (ID_COFRE),
    CONSTRAINT FK_COFRE_CARTEIRA FOREIGN KEY (ID_CARTEIRA) 
        REFERENCES TB_CARTEIRA (ID_CARTEIRA),
    CONSTRAINT FK_COFRE_CRIPTOATIVO FOREIGN KEY (ID_CRIPTOATIVO) 
        REFERENCES TB_CRIPTOATIVO (ID_CRIPTOATIVO),
    CONSTRAINT CK_COFRE_STATUS CHECK (ST_COFRE IN ('BLOQUEADO', 'RESGATADO', 'CANCELADO')),
    CONSTRAINT CK_COFRE_QT_BLOQUEADA CHECK (QT_BLOQUEADA > 0),
    CONSTRAINT CK_COFRE_DATA_LIBERACAO CHECK (DT_LIBERACAO >= DT_CRIACAO)
);

-- TABELA: TB_GUARDIAO
-- Usuários autorizados a votar em operações corporativas de empresas
CREATE TABLE TB_GUARDIAO (
    ID_GUARDIAO              NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO               NUMBER NOT NULL,
    ID_EMPRESA               NUMBER NOT NULL,
    DT_NOMEACAO              DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
    FL_ATIVO                 CHAR(1) DEFAULT 'S' NOT NULL,
    
    CONSTRAINT PK_TB_GUARDIAO PRIMARY KEY (ID_GUARDIAO),
    CONSTRAINT UK_GUARDIAO_USUARIO_EMPRESA UNIQUE (ID_USUARIO, ID_EMPRESA),
    CONSTRAINT FK_GUARDIAO_USUARIO FOREIGN KEY (ID_USUARIO) 
        REFERENCES TB_USUARIO (ID_USUARIO),
    CONSTRAINT FK_GUARDIAO_EMPRESA FOREIGN KEY (ID_EMPRESA) 
        REFERENCES TB_EMPRESA (ID_EMPRESA),
    CONSTRAINT CK_GUARDIAO_ATIVO CHECK (FL_ATIVO IN ('S', 'N'))
);

-- TABELA: TB_SOLICITACAO_TRANSACAO
-- Solicitações multi-assinatura corporativas que requerem quórum de aprovação
CREATE TABLE TB_SOLICITACAO_TRANSACAO (
    ID_SOLICITACAO           NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_EMPRESA               NUMBER NOT NULL,
    ID_TRANSACAO             NUMBER NOT NULL,
    NR_QUORUM_MINIMO         NUMBER(3) DEFAULT 2 NOT NULL,
    DH_EXPIRACAO             TIMESTAMP NOT NULL,
    ST_SOLICITACAO           VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    DH_CRIACAO               TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    
    CONSTRAINT PK_TB_SOLICITACAO PRIMARY KEY (ID_SOLICITACAO),
    CONSTRAINT FK_SOLICITACAO_EMPRESA FOREIGN KEY (ID_EMPRESA) 
        REFERENCES TB_EMPRESA (ID_EMPRESA),
    CONSTRAINT FK_SOLICITACAO_TRANSACAO FOREIGN KEY (ID_TRANSACAO) 
        REFERENCES TB_TRANSACAO (ID_TRANSACAO),
    CONSTRAINT CK_SOLICITACAO_STATUS CHECK (ST_SOLICITACAO IN (
        'PENDENTE', 'APROVADA', 'REJEITADA', 'EXPIRADA'
    )),
    CONSTRAINT CK_SOLICITACAO_QUORUM CHECK (NR_QUORUM_MINIMO > 0)
);

-- TABELA: TB_AULA
-- Módulos educacionais gamificados da plataforma Aurum
CREATE TABLE TB_AULA (
    ID_AULA                  NUMBER GENERATED ALWAYS AS IDENTITY,
    NM_TITULO                VARCHAR2(150) NOT NULL,
    DS_CONTEUDO              VARCHAR2(4000) NOT NULL,
    NR_ORDEM                 NUMBER(4) NOT NULL,
    QT_XP_RECOMPENSA         NUMBER(6) DEFAULT 50 NOT NULL,
    
    CONSTRAINT PK_TB_AULA PRIMARY KEY (ID_AULA),
    CONSTRAINT UK_AULA_ORDEM UNIQUE (NR_ORDEM),
    CONSTRAINT CK_AULA_ORDEM_POSITIVA CHECK (NR_ORDEM > 0),
    CONSTRAINT CK_AULA_XP_POSITIVO CHECK (QT_XP_RECOMPENSA >= 0)
);

-- TABELA: TB_PROGRESSO_AULA
-- Acompanhamento pedagógico e recompensas do usuário
CREATE TABLE TB_PROGRESSO_AULA (
    ID_PROGRESSO             NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO               NUMBER NOT NULL,
    ID_AULA                  NUMBER NOT NULL,
    FL_CONCLUIDA             CHAR(1) DEFAULT 'N' NOT NULL,
    DT_CONCLUSAO             DATE,
    
    CONSTRAINT PK_TB_PROGRESSO_AULA PRIMARY KEY (ID_PROGRESSO),
    CONSTRAINT UK_PROGRESSO_USUARIO_AULA UNIQUE (ID_USUARIO, ID_AULA),
    CONSTRAINT FK_PROGRESSO_USUARIO FOREIGN KEY (ID_USUARIO) 
        REFERENCES TB_USUARIO (ID_USUARIO),
    CONSTRAINT FK_PROGRESSO_AULA FOREIGN KEY (ID_AULA) 
        REFERENCES TB_AULA (ID_AULA),
    CONSTRAINT CK_PROGRESSO_CONCLUIDA CHECK (FL_CONCLUIDA IN ('S', 'N'))
);
