-- ============================================================================
-- PROJETO: AURUM BANKING
-- ETAPA 1: MODELAGEM E SCRIPT DML (ORACLE DATABASE / SQL DEVELOPER)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. CARGA DE DADOS INICIAIS (INSERTS)
-- ----------------------------------------------------------------------------

-- Inserindo Carteiras Digitais
INSERT INTO TB_CARTEIRA (DS_ENDERECO_DIGITAL, VL_SALDO_DISPONIVEL_BRL)
VALUES ('0x71C...A891_CARTEIRA_JOAO', 15450.00);

INSERT INTO TB_CARTEIRA (DS_ENDERECO_DIGITAL, VL_SALDO_DISPONIVEL_BRL)
VALUES ('0x34B...F122_CARTEIRA_MARIA', 8200.50);

INSERT INTO TB_CARTEIRA (DS_ENDERECO_DIGITAL, VL_SALDO_DISPONIVEL_BRL)
VALUES ('0x99D...C443_CARTEIRA_CARLOS', 1200.00);

INSERT INTO TB_CARTEIRA (DS_ENDERECO_DIGITAL, VL_SALDO_DISPONIVEL_BRL)
VALUES ('0x55E...B774_CARTEIRA_ANA', 25000.00);

INSERT INTO TB_CARTEIRA (DS_ENDERECO_DIGITAL, VL_SALDO_DISPONIVEL_BRL)
VALUES ('0xCORP...0001_CARTEIRA_TECHINNOV', 350000.00);

INSERT INTO TB_CARTEIRA (DS_ENDERECO_DIGITAL, VL_SALDO_DISPONIVEL_BRL)
VALUES ('0xCORP...0002_CARTEIRA_AURUMCORP', 1200000.00);

-- Inserindo Usuários (Pessoa Física)
INSERT INTO TB_USUARIO (
    NM_COMPLETO, NR_CPF, DS_EMAIL, DS_SENHA_HASH, DT_NASCIMENTO, 
    DS_MODO_INTERFACE, VL_LIMITE_MENSAL, FL_KYC_APROVADO, ID_CARTEIRA
) VALUES (
    'João Ricardo Silva', '12345678901', 'joao.ricardo@aurumbank.com',
    '$2a$12$e8Yh9Zf5G7k1V2x.8N4M.uO7pW4L5k8J2n6H3k9L1p4Q7r2T8v0W.',
    TO_DATE('1995-03-15', 'YYYY-MM-DD'), 'INICIANTE', 5000.00, 'N', 1
);

INSERT INTO TB_USUARIO (
    NM_COMPLETO, NR_CPF, DS_EMAIL, DS_SENHA_HASH, DT_NASCIMENTO, 
    DS_MODO_INTERFACE, VL_LIMITE_MENSAL, FL_KYC_APROVADO, ID_CARTEIRA
) VALUES (
    'Maria Eduarda Souza', '98765432100', 'maria.souza@gmail.com',
    '$2a$12$j4Kn7V2x9Zf5G7k1E8Yh.uO7pW4L5k8J2n6H3k9L1p4Q7r2T8v0X.',
    TO_DATE('1988-07-22', 'YYYY-MM-DD'), 'AVANCADO', 50000.00, 'S', 2
);

INSERT INTO TB_USUARIO (
    NM_COMPLETO, NR_CPF, DS_EMAIL, DS_SENHA_HASH, DT_NASCIMENTO, 
    DS_MODO_INTERFACE, VL_LIMITE_MENSAL, FL_KYC_APROVADO, ID_CARTEIRA
) VALUES (
    'Carlos Alberto Santos', '45678912345', 'carlos.alberto@techcorp.com.br',
    '$2a$12$k8J2n6H3k9L1p4Q7r2T8.e8Yh9Zf5G7k1V2x.8N4M.uO7pW4L5v1Y.',
    TO_DATE('1992-11-05', 'YYYY-MM-DD'), 'AVANCADO', 100000.00, 'S', 3
);

INSERT INTO TB_USUARIO (
    NM_COMPLETO, NR_CPF, DS_EMAIL, DS_SENHA_HASH, DT_NASCIMENTO, 
    DS_MODO_INTERFACE, VL_LIMITE_MENSAL, FL_KYC_APROVADO, ID_CARTEIRA
) VALUES (
    'Ana Beatriz Lima', '78912345678', 'ana.lima@investdigital.io',
    '$2a$12$uO7pW4L5k8J2n6H3k9L1.e8Yh9Zf5G7k1V2x.8N4M.p4Q7r2T8v2Z.',
    TO_DATE('2000-01-30', 'YYYY-MM-DD'), 'INICIANTE', 5000.00, 'N', 4
);

-- Inserindo Empresas (Pessoa Jurídica)
INSERT INTO TB_EMPRESA (
    DS_RAZAO_SOCIAL, NR_CNPJ, DS_EMAIL_CORPORATIVO, FL_STATUS_ATIVO, ID_USUARIO_MASTER, ID_CARTEIRA
) VALUES (
    'Tech Innovators Soluções Digitais LTDA', '12345678000195', 'contato@techinnov.com.br', 'S', 2, 5
);

INSERT INTO TB_EMPRESA (
    DS_RAZAO_SOCIAL, NR_CNPJ, DS_EMAIL_CORPORATIVO, FL_STATUS_ATIVO, ID_USUARIO_MASTER, ID_CARTEIRA
) VALUES (
    'Aurum Capital Participações S.A.', '98765432000188', 'financeiro@aurumcapital.com', 'S', 3, 6
);

-- Inserindo Criptoativos
INSERT INTO TB_CRIPTOATIVO (NM_CRIPTOATIVO, CD_SIGLA, DS_LOGO_URL, VL_PRECO_ATUAL_BRL, PC_VARIACAO_24H, FL_ATIVO_NEGOCIACAO)
VALUES ('Bitcoin', 'BTC', 'https://assets.aurum.com/icons/btc.svg', 342500.0000, 2.4500, 'S');

INSERT INTO TB_CRIPTOATIVO (NM_CRIPTOATIVO, CD_SIGLA, DS_LOGO_URL, VL_PRECO_ATUAL_BRL, PC_VARIACAO_24H, FL_ATIVO_NEGOCIACAO)
VALUES ('Ethereum', 'ETH', 'https://assets.aurum.com/icons/eth.svg', 18200.0000, -1.1500, 'S');

INSERT INTO TB_CRIPTOATIVO (NM_CRIPTOATIVO, CD_SIGLA, DS_LOGO_URL, VL_PRECO_ATUAL_BRL, PC_VARIACAO_24H, FL_ATIVO_NEGOCIACAO)
VALUES ('Solana', 'SOL', 'https://assets.aurum.com/icons/sol.svg', 890.5000, 5.8000, 'S');

INSERT INTO TB_CRIPTOATIVO (NM_CRIPTOATIVO, CD_SIGLA, DS_LOGO_URL, VL_PRECO_ATUAL_BRL, PC_VARIACAO_24H, FL_ATIVO_NEGOCIACAO)
VALUES ('Aurum Gold Token', 'AURG', 'https://assets.aurum.com/icons/aurg.svg', 315.7500, 0.2000, 'S');

-- Inserindo Posições de Criptoativos por Carteira
INSERT INTO TB_POSICAO_CRIPTO (ID_CARTEIRA, ID_CRIPTOATIVO, QT_TOTAL)
VALUES (1, 1, 0.05000000); -- João: 0.05 BTC

INSERT INTO TB_POSICAO_CRIPTO (ID_CARTEIRA, ID_CRIPTOATIVO, QT_TOTAL)
VALUES (1, 2, 0.85000000); -- João: 0.85 ETH

INSERT INTO TB_POSICAO_CRIPTO (ID_CARTEIRA, ID_CRIPTOATIVO, QT_TOTAL)
VALUES (2, 1, 0.50000000); -- Maria: 0.50 BTC

INSERT INTO TB_POSICAO_CRIPTO (ID_CARTEIRA, ID_CRIPTOATIVO, QT_TOTAL)
VALUES (2, 3, 25.00000000); -- Maria: 25.00 SOL

INSERT INTO TB_POSICAO_CRIPTO (ID_CARTEIRA, ID_CRIPTOATIVO, QT_TOTAL)
VALUES (5, 1, 1.25000000); -- TechInnov: 1.25 BTC

INSERT INTO TB_POSICAO_CRIPTO (ID_CARTEIRA, ID_CRIPTOATIVO, QT_TOTAL)
VALUES (5, 4, 500.00000000); -- TechInnov: 500 AURG

-- Inserindo Transações Contábeis e Operacionais
INSERT INTO TB_TRANSACAO (
    TP_TRANSACAO, ST_TRANSACAO, VL_MOVIMENTADO_BRL, QT_CRIPTO, 
    VL_COTACAO_MOMENTO, VL_TAXA_OPERACAO, ID_CARTEIRA, ID_CRIPTOATIVO
) VALUES (
    'DEPOSITO_FIAT', 'CONCLUIDA', 20000.00, 0.00000000, 0.0000, 0.00, 1, NULL
);

INSERT INTO TB_TRANSACAO (
    TP_TRANSACAO, ST_TRANSACAO, VL_MOVIMENTADO_BRL, QT_CRIPTO, 
    VL_COTACAO_MOMENTO, VL_TAXA_OPERACAO, ID_CARTEIRA, ID_CRIPTOATIVO
) VALUES (
    'COMPRA', 'CONCLUIDA', 17125.00, 0.05000000, 342500.0000, 15.00, 1, 1
);

INSERT INTO TB_TRANSACAO (
    TP_TRANSACAO, ST_TRANSACAO, VL_MOVIMENTADO_BRL, QT_CRIPTO, 
    VL_COTACAO_MOMENTO, VL_TAXA_OPERACAO, ID_CARTEIRA, ID_CRIPTOATIVO
) VALUES (
    'COMPRA', 'CONCLUIDA', 15470.00, 0.85000000, 18200.0000, 12.50, 1, 2
);

INSERT INTO TB_TRANSACAO (
    TP_TRANSACAO, ST_TRANSACAO, VL_MOVIMENTADO_BRL, QT_CRIPTO, 
    VL_COTACAO_MOMENTO, VL_TAXA_OPERACAO, ID_CARTEIRA, ID_CRIPTOATIVO
) VALUES (
    'COMPRA', 'CONCLUIDA', 171250.00, 0.50000000, 342500.0000, 50.00, 2, 1
);

INSERT INTO TB_TRANSACAO (
    TP_TRANSACAO, ST_TRANSACAO, VL_MOVIMENTADO_BRL, QT_CRIPTO, 
    VL_COTACAO_MOMENTO, VL_TAXA_OPERACAO, ID_CARTEIRA, ID_CRIPTOATIVO
) VALUES (
    'COMPRA', 'PROCESSANDO', 428125.00, 1.25000000, 342500.0000, 100.00, 5, 1
);

-- Inserindo Cofre Temporal (HODL programado)
INSERT INTO TB_COFRE_TEMPORAL (
    NM_OBJETIVO, DT_CRIACAO, DT_LIBERACAO, QT_BLOQUEADA, ST_COFRE, ID_CARTEIRA, ID_CRIPTOATIVO
) VALUES (
    'Reserva de Longo Prazo 2027', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 0.02500000, 'BLOQUEADO', 1, 1
);

INSERT INTO TB_COFRE_TEMPORAL (
    NM_OBJETIVO, DT_CRIACAO, DT_LIBERACAO, QT_BLOQUEADA, ST_COFRE, ID_CARTEIRA, ID_CRIPTOATIVO
) VALUES (
    'Fundo de Inovação Tecnológica', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 6), 10.00000000, 'BLOQUEADO', 2, 3
);

-- Inserindo Guardiões de Empresas (Multi-assinatura)
INSERT INTO TB_GUARDIAO (ID_USUARIO, ID_EMPRESA, FL_ATIVO)
VALUES (2, 1, 'S'); -- Maria é guardiã da Tech Innovators

INSERT INTO TB_GUARDIAO (ID_USUARIO, ID_EMPRESA, FL_ATIVO)
VALUES (3, 1, 'S'); -- Carlos é guardião da Tech Innovators

INSERT INTO TB_GUARDIAO (ID_USUARIO, ID_EMPRESA, FL_ATIVO)
VALUES (1, 2, 'S'); -- João é guardião da Aurum Capital

INSERT INTO TB_GUARDIAO (ID_USUARIO, ID_EMPRESA, FL_ATIVO)
VALUES (3, 2, 'S'); -- Carlos é guardião da Aurum Capital

-- Inserindo Solicitação de Transação Corporativa Multi-Assinatura
INSERT INTO TB_SOLICITACAO_TRANSACAO (
    ID_EMPRESA, ID_TRANSACAO, NR_QUORUM_MINIMO, DH_EXPIRACAO, ST_SOLICITACAO
) VALUES (
    1, 5, 2, SYSTIMESTAMP + INTERVAL '2' DAY, 'PENDENTE'
);

-- Inserindo Módulos de Educação Financeira (Aulas)
INSERT INTO TB_AULA (NM_TITULO, DS_CONTEUDO, NR_ORDEM, QT_XP_RECOMPENSA)
VALUES (
    'Introdução à Autocustódia e Segurança', 
    'Aprenda como funcionam chaves privadas, endereços públicos e boas práticas de segurança em criptoativos.',
    1, 100
);

INSERT INTO TB_AULA (NM_TITULO, DS_CONTEUDO, NR_ORDEM, QT_XP_RECOMPENSA)
VALUES (
    'Gestão de Risco e Volatilidade', 
    'Como calcular dimensionamento de posição, balanceamento de carteira e proteção patrimonial.',
    2, 150
);

INSERT INTO TB_AULA (NM_TITULO, DS_CONTEUDO, NR_ORDEM, QT_XP_RECOMPENSA)
VALUES (
    'Governança Corporativa e Multi-Assinatura', 
    'Compreenda o papel dos guardiões e quóruns de autorização em tesourarias empresariais.',
    3, 200
);

-- Inserindo Progresso dos Usuários nas Aulas
INSERT INTO TB_PROGRESSO_AULA (ID_USUARIO, ID_AULA, FL_CONCLUIDA, DT_CONCLUSAO)
VALUES (1, 1, 'S', TRUNC(SYSDATE - 2));

INSERT INTO TB_PROGRESSO_AULA (ID_USUARIO, ID_AULA, FL_CONCLUIDA, DT_CONCLUSAO)
VALUES (1, 2, 'N', NULL);

INSERT INTO TB_PROGRESSO_AULA (ID_USUARIO, ID_AULA, FL_CONCLUIDA, DT_CONCLUSAO)
VALUES (2, 1, 'S', TRUNC(SYSDATE - 10));

INSERT INTO TB_PROGRESSO_AULA (ID_USUARIO, ID_AULA, FL_CONCLUIDA, DT_CONCLUSAO)
VALUES (2, 2, 'S', TRUNC(SYSDATE - 5));

INSERT INTO TB_PROGRESSO_AULA (ID_USUARIO, ID_AULA, FL_CONCLUIDA, DT_CONCLUSAO)
VALUES (2, 3, 'S', TRUNC(SYSDATE - 1));

-- ----------------------------------------------------------------------------
-- 2. ATUALIZAÇÃO DE REGISTROS (UPDATES)
-- ----------------------------------------------------------------------------

-- Atualização 1: Aprovação de KYC e upgrade de perfil e limite de usuário
UPDATE TB_USUARIO
   SET FL_KYC_APROVADO   = 'S',
       VL_LIMITE_MENSAL  = 25000.00,
       DS_MODO_INTERFACE = 'AVANCADO'
 WHERE ID_USUARIO = 1;

-- Atualização 2: Atualização de cotação de mercado e variação 24h do Bitcoin
UPDATE TB_CRIPTOATIVO
   SET VL_PRECO_ATUAL_BRL    = 351200.0000,
       PC_VARIACAO_24H       = 4.1500,
       DH_ULTIMA_ATUALIZACAO = SYSTIMESTAMP
 WHERE CD_SIGLA = 'BTC';

-- Atualização 3: Conclusão de transação após validação da rede
UPDATE TB_TRANSACAO
   SET ST_TRANSACAO = 'CONCLUIDA'
 WHERE ID_TRANSACAO = 5;

-- Atualização 4: Atualização de e-mail de contato corporativo
UPDATE TB_EMPRESA
   SET DS_EMAIL_CORPORATIVO = 'contato.operacoes@techinnov.com.br'
 WHERE ID_EMPRESA = 1;

-- ----------------------------------------------------------------------------
-- 3. REMOÇÃO DE REGISTROS (DELETES COM RESPEITO À INTEGRIDADE REFERENCIAL)
-- ----------------------------------------------------------------------------

-- Remoção 1: Remoção de progresso de aula não finalizado para reteste do usuário
DELETE FROM TB_PROGRESSO_AULA
 WHERE ID_USUARIO = 1
   AND ID_AULA = 2
   AND FL_CONCLUIDA = 'N';

-- Remoção 2: Desativação/remoção de guardião inativo específico
DELETE FROM TB_GUARDIAO
 WHERE ID_USUARIO = 1
   AND ID_EMPRESA = 2;

-- ----------------------------------------------------------------------------
-- 4. CONSULTAS DE VALIDAÇÃO E RELATÓRIOS (SELECTS COM JOINS)
-- ----------------------------------------------------------------------------

-- Consulta 1: Extrato Consolidado de Clientes (Pessoa Física) com Carteira e Saldo
SELECT 
    u.ID_USUARIO,
    u.NM_COMPLETO,
    u.NR_CPF,
    u.DS_EMAIL,
    u.DS_MODO_INTERFACE,
    u.FL_KYC_APROVADO,
    u.VL_LIMITE_MENSAL,
    c.DS_ENDERECO_DIGITAL,
    c.VL_SALDO_DISPONIVEL_BRL
FROM TB_USUARIO u
INNER JOIN TB_CARTEIRA c ON u.ID_CARTEIRA = c.ID_CARTEIRA
ORDER BY u.ID_USUARIO;

-- Consulta 2: Posição Patrimonial em Criptoativos por Carteira e Usuário
SELECT 
    u.NM_COMPLETO AS CLIENTE,
    c.DS_ENDERECO_DIGITAL AS CARTEIRA,
    a.CD_SIGLA AS ATIVO,
    a.NM_CRIPTOATIVO AS NOME_CRIPTO,
    p.QT_TOTAL AS QUANTIDADE,
    a.VL_PRECO_ATUAL_BRL AS COTACAO_ATUAL_BRL,
    ROUND(p.QT_TOTAL * a.VL_PRECO_ATUAL_BRL, 2) AS VALOR_TOTAL_BRL
FROM TB_POSICAO_CRIPTO p
INNER JOIN TB_CARTEIRA c ON p.ID_CARTEIRA = c.ID_CARTEIRA
INNER JOIN TB_USUARIO u ON c.ID_CARTEIRA = u.ID_CARTEIRA
INNER JOIN TB_CRIPTOATIVO a ON p.ID_CRIPTOATIVO = a.ID_CRIPTOATIVO
WHERE p.QT_TOTAL > 0
ORDER BY VALOR_TOTAL_BRL DESC;

-- Consulta 3: Histórico de Transações Detalhado com Ativo e Carteira Vinculada
SELECT 
    t.ID_TRANSACAO,
    t.DH_TRANSACAO,
    t.TP_TRANSACAO,
    t.ST_TRANSACAO,
    NVL(a.CD_SIGLA, 'FIAT (BRL)') AS ATIVO,
    t.QT_CRIPTO,
    t.VL_COTACAO_MOMENTO,
    t.VL_MOVIMENTADO_BRL,
    t.VL_TAXA_OPERACAO,
    c.DS_ENDERECO_DIGITAL AS CARTEIRA_ORIGEM
FROM TB_TRANSACAO t
INNER JOIN TB_CARTEIRA c ON t.ID_CARTEIRA = c.ID_CARTEIRA
LEFT JOIN TB_CRIPTOATIVO a ON t.ID_CRIPTOATIVO = a.ID_CRIPTOATIVO
ORDER BY t.DH_TRANSACAO DESC;

-- Consulta 4: Governança Corporativa - Empresas, Usuário Master e Seus Guardiões
SELECT 
    e.DS_RAZAO_SOCIAL AS EMPRESA,
    e.NR_CNPJ AS CNPJ,
    u_master.NM_COMPLETO AS USUARIO_MASTER,
    u_guard.NM_COMPLETO AS GUARDIAO_DESIGNADO,
    g.DT_NOMEACAO,
    g.FL_ATIVO AS GUARDIAO_ATIVO
FROM TB_EMPRESA e
INNER JOIN TB_USUARIO u_master ON e.ID_USUARIO_MASTER = u_master.ID_USUARIO
INNER JOIN TB_GUARDIAO g ON e.ID_EMPRESA = g.ID_EMPRESA
INNER JOIN TB_USUARIO u_guard ON g.ID_USUARIO = u_guard.ID_USUARIO
ORDER BY e.DS_RAZAO_SOCIAL, u_guard.NM_COMPLETO;

-- Consulta 5: Relatório de Cofres Temporais (HODL) e Prazos de Liberação
SELECT 
    cof.ID_COFRE,
    u.NM_COMPLETO AS TITULAR,
    cof.NM_OBJETIVO,
    a.CD_SIGLA AS ATIVO,
    cof.QT_BLOQUEADA,
    cof.DT_CRIACAO,
    cof.DT_LIBERACAO,
    CASE 
        WHEN TRUNC(SYSDATE) >= cof.DT_LIBERACAO THEN 'LIBERADO PARA RESGATE'
        ELSE 'BLOQUEADO EM CARÊNCIA'
    END AS STATUS_TEMPORAL,
    cof.ST_COFRE
FROM TB_COFRE_TEMPORAL cof
INNER JOIN TB_CARTEIRA c ON cof.ID_CARTEIRA = c.ID_CARTEIRA
INNER JOIN TB_USUARIO u ON c.ID_CARTEIRA = u.ID_CARTEIRA
INNER JOIN TB_CRIPTOATIVO a ON cof.ID_CRIPTOATIVO = a.ID_CRIPTOATIVO
ORDER BY cof.DT_LIBERACAO ASC;

-- Consulta 6: Painel Gamificado de Educação - Aulas Concluídas e XP Acumulado
SELECT 
    u.NM_COMPLETO AS ALUNO,
    COUNT(CASE WHEN p.FL_CONCLUIDA = 'S' THEN 1 END) AS AULAS_CONCLUIDAS,
    NVL(SUM(CASE WHEN p.FL_CONCLUIDA = 'S' THEN au.QT_XP_RECOMPENSA ELSE 0 END), 0) AS TOTAL_XP_GANHO
FROM TB_USUARIO u
LEFT JOIN TB_PROGRESSO_AULA p ON u.ID_USUARIO = p.ID_USUARIO
LEFT JOIN TB_AULA au ON p.ID_AULA = au.ID_AULA
GROUP BY u.ID_USUARIO, u.NM_COMPLETO
ORDER BY TOTAL_XP_GANHO DESC;

-- ----------------------------------------------------------------------------
-- 5. CONFIRMAÇÃO DAS TRANSAÇÕES
-- ----------------------------------------------------------------------------
COMMIT;
